### ISSUE TITLE
Windows and Subtitles:

### ISSUE THREAD

**Issue by maimteve** [u8sand/Baka-MPlayer#88] opened 2015-01-28 20:38 UTC
Windows 7
64 bit

2.0.2 - External .srt subtitle files will not display . Internal subtitle files work. 
1.5 - All subtitles work. 

These subtitles work in mainline mpv and other programs as well.

**Comment by u8sand** [comment] 2015-01-29 01:47
@maimteve this is a bug related to fontconfig that we have yet to solve for Windows.  Subtitles which define their fonts explicitly should work correctly.  In the near future we will patch this, sorry for any inconveniences in the meantime.

**Comment by maimteve** [comment] 2015-02-04 23:39
I would recommend placing this as the top priority to fix.  It's the main reason I'm not recommending bakamplayer to new users. Once it's fixed I will. 

I don't recommend stand alone mpv to new users either, since it's too different for them and they'll just be confused. They need something like bakamplayer that acts as a more traditional media player.

**Comment by godly-devotion** [comment] 2015-02-07 02:11
@maimteve Rest assured we are actively looking for a solution. However the problem is a bit harder than expected. In the meantime, you can use pre-`v2.0` Baka MPlayer which should have no problems.

**Comment by u8sand** [comment] 2015-02-08 23:25
I'll note that with 587a0491e1ba0a4bb072aae48c67939afe2e8b48 a patch which fixes fontconfig on mxe has been added. There are still some things which need to be done (due to fontconfig's slow caching).

**Comment by amazingfate** [comment] 2015-02-15 13:40
I built the git version today with MSYS2 and the .srt subtitiles can be showed but only English subtitles looks fine, other languages are like this:
![srt](https://cloud.githubusercontent.com/assets/5022901/6203394/ddd5002e-b55a-11e4-958a-0c8ffd9f4623.jpg)

**Comment by u8sand** [comment] 2015-02-15 15:32
@amazingfate I see, for now then we'd have to just make that config available for people.
Does showtext work?  (command-line: `mpv show_text Hello`)

**Comment by amazingfate** [comment] 2015-02-16 00:59
showtext works but it will make the video back to the start

**Comment by u8sand** [comment] 2015-02-16 13:28
@amazingfate that's strange.. what about the media-info? (`tab`) If that works fine we can masquerade `show_text`.

**Comment by amazingfate** [comment] 2015-02-17 01:07
@u8sand media-info works.

**Comment by godly-devotion** [comment] 2015-02-25 02:29
@maimteve sorry for taking so long. here is a working (un)official build that has the external sub files fixed. unfortunately it will take a bit more time until it will be fully fixed as we haven't got static building working for Windows yet, thus the messy dll's required.

Download: https://db.tt/cwPmrHMw

**Comment by maimteve** [comment] 2015-02-27 04:08
@godly-devotion 
Thank you. I will point people to that build for the time being.

**Comment by godly-devotion** [comment] 2015-06-04 13:51
Fixed with latest version.

**Closed by godly-devotion** 2015-06-04 13:51 UTC
Labels: bug
